### ISSUE TITLE
"Butterfly is still initializing..." <- Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException

### ISSUE THREAD

**Issue by hhkaos** [stkenny/grefine-rdf-extension#50]
Hi there!

I just wanted to make sure that the extension is not working with OpenRefine v3.4.1, right?

I got this error while I was trying to start it:

```
05:36:38.240 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
05:36:38.246 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resources/webapp' (6ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/OpenRefine.app/Contents/Java/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Applications/OpenRefine.app/Contents/Resources/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
05:36:38.602 [                   refine] Starting OpenRefine 3.2 [55c921b]... (356ms)
05:36:38.602 [                   refine] initializing FileProjectManager with dir (0ms)
05:36:38.602 [                   refine] /Users/hhkaos/Library/Application Support/OpenRefine (0ms)
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:351)
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:424)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:812)
	at org.mozilla.javascript.NativeJavaClass.initMembers(NativeJavaClass.java:49)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:43)
	at org.mozilla.javascript.NativeJavaClass.<init>(NativeJavaClass.java:39)
	at org.mozilla.javascript.WrapFactory.wrapJavaClass(WrapFactory.java:139)
	at org.mozilla.javascript.NativeJavaPackage.getPkgProperty(NativeJavaPackage.java:135)
	at org.mozilla.javascript.NativeJavaPackage.get(NativeJavaPackage.java:84)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2313)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1579)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1572)
	at org.mozilla.javascript.gen.file__Users_hhkaos_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10._c_script_0(file:/Users/hhkaos/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js:4)
	at org.mozilla.javascript.gen.file__Users_hhkaos_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/Users/hhkaos/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__Users_hhkaos_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/Users/hhkaos/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at org.mozilla.javascript.gen.file__Users_hhkaos_Library_Application_20Support_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10.exec(file:/Users/hhkaos/Library/Application%20Support/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.initScope(ButterflyModuleImpl.java:619)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:629)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```
I finally end up installing [OpenRefine v3.1](https://github.com/OpenRefine/OpenRefine/releases/tag/3.1) and now it works ^_^.

Changing the subject, a quick suggestion, on the [installation guidelines](https://github.com/stkenny/grefine-rdf-extension#from-compiled-release) you just say: `Restart OpenRefine` . I took me some time until I figured out how to restart OpenRefine on Mac xD. I found the solution on [StackOverflow > Find (and kill) process locking port 3000 on Mac].

I also add the problem [uncompressing the wrong zip file](https://github.com/stkenny/grefine-rdf-extension/issues/23). Maybe to point it out in the installation guidelines would be nice.

That's all.... and thanks for your awesome job!! 😄

**Comment by stkenny** [comment]
Hi, it should work with 3.4.1. From that error though it seems you are running 3.2?

05:36:38.602 [                   refine] Starting OpenRefine 3.2 [55c921b]... (356ms)

**Comment by stkenny** [comment]
Works with 3.4.
